default:
  image: node:latest

stages:
  - build
  - deploy

cache:
  key: ${CI_COMMIT_REF_SLUG}
  paths:
    - node_modules/

build:
  stage: build
  script:
    - npm ci
    - npm run build
  artifacts:
    paths:
      - .next/

deploy_preview:
  stage: deploy
  only:
    - development
  script:
    - npm update
    - npm install -g vercel
    - $env:PATH = [System.Environment]::GetEnvironmentVariable("PATH", [System.EnvironmentVariableTarget]::Machine) + ";" + [System.Environment]::GetEnvironmentVariable("PATH", [System.EnvironmentVariableTarget]::Process)
    - vercel pull --yes --environment=preview --token=0Zmz5O1hMzEa6BVw9XacmLqr
    - vercel deploy --token=0Zmz5O1hMzEa6BVw9XacmLqr

deploy_production:
  stage: deploy
  only:
    - master
  script:
    - npm update
    - npm install -g vercel
    - $env:PATH = [System.Environment]::GetEnvironmentVariable("PATH", [System.EnvironmentVariableTarget]::Machine) + ";" + [System.Environment]::GetEnvironmentVariable("PATH", [System.EnvironmentVariableTarget]::Process)
    - vercel pull --yes --environment=production --token=0Zmz5O1hMzEa6BVw9XacmLqr
    - vercel deploy --prod --token=0Zmz5O1hMzEa6BVw9XacmLqr