export const barangAll = [
    'Apples',
    'Almonds',
    'Avocados',
    'Bananas',
    'Batteries',
    'Bread',
    'Canned Beans',
    'Canned Soup',
    'Canned Vegetables',
    'Cheese',
    'Chicken',
    'Cleaning Supplies',
    'Coffee',
    'Cookies',
    'Cooking Oil',
    'Diapers',
    'Eggs',
    'Frozen Pizza',
    'Ice Cream',
    'Juice',
    'Kale',
    'Laundry Detergent',
    'Lightbulbs',
    'Milk',
    'Onions',
    'Paper Towels',
    'Pasta',
    'Pet Food',
    'Potatoes',
    'Rice',
    'Shampoo',
    'Soap',
    'Soda',
    'Spinach',
    'Spices',
    'Tea',
    'Toilet Paper',
    'Tomatoes',
    'Toothpaste',
    'Water',
    'Yogurt',
];